### PR TITLE
Support for optional handler of successful enforce calls

### PR DESCRIPTION
**Pull request by elight**
I'm expecting to write one or a few gems that I intend to play nicely with canable.  However, I found myself in the position of needing to monkey patch/alias method chain.  As I basically hate monkey patching, I thought it better to add support for an optional Observer-like behavior.

In this case, when an enforce\* method is called, it will call a "handle_enforce" method on the controller if the controller responds to that message.

### CODE REVIEW

**Comment by jnunemaker** [comment]
Yo. Not sure I get the point of this. Can you elaborate? Seems like you could just override and call super rather than alias method chain. Also, what are you doing in addition to the default in your handle_enforce method?

**Comment by elight** [comment]
Thanks for responding so quickly.

It's not my goal to subclass classes including Canable modules. Instead, among other things, I'm planning to write a simple gem to define an after_filter on ApplicationController to raise if no enforce is called in an action or some skip method is called. 

The feature from CanCan is handy for me and for more junior devs on a project that I'm working on: making sure they dot their i's and cross their t's.

Specifically, I don't want to add the above feature to Canable. I plan on using this hook to implement the after_filter check.

I respect that Canable intentionally as a narrow focus. I hope to build some gems that work similarly but collaborate with Canable.

**Comment by elight** [comment]
Hrm I suppose I could implement my feature by writing an initializer that checks keys for every class that includes Canable, override the enforcer methods for them then call super as you say.  Seems a bit hairy to find the Canable-ized classes that way. Sure, I can walk the ObjectSpace for that.

**Comment by jnunemaker** [comment]
Because you include canable, it is put in the ancestor chain. This means you can override it and use super to add functionality without doing any inheritance shenanigans.

I get wanting to check that people are using some form of enforce. What I don't get is how another instance method gets you there. I'm not familiar with cancan. Maybe you can link some code that shows how this is useful using cancan?

**Comment by elight** [comment]
Oh I get the ancestor chain part.

In a nutshell, I would use handle_enforce to record which action
called the enforce method with which resource (like in the test).  I
would then have an after_filter that would probably use caller to
determine which action was called, check the array I'd accumulate in
handle_enforce, and raise if that action wasn't enforced.  If it was
enforced, I'd go on my merry way.

The idea is based on this feature:
https://github.com/ryanb/cancan/wiki/Ensure-Authorization

The hook just lets me record calls to review them later.

Unfortunately, my ObjectSpace initializer idea, I realize wont work
because models are lazily loaded.  This hook would make it far
simpler.

Though another alternative would be to include another module after
Canable that overrides the enforce methods calling super. Maybe that's
where you were going earlier.  That's actually cleaner, requiring no
changes to Canable.  I like it.

Thanks for the dialog.

On Apr 23, 2012, at 11:02 PM, John Nunemaker
reply@reply.github.com
wrote:

**Comment by jnunemaker** [comment]
Yep that was what I was aiming for. Sweet.

**Pull request closed without merging**
